### ISSUE TITLE
Errors passed to logger as details never make it to the logs

### ISSUE THREAD

**Issue by gcsabbagh** [SSENSE/node-logger#19]
If we try to use JSON.stringify on an error then we get no output.

We can utilize the [replacer](https://stackoverflow.com/questions/18391212/is-it-not-possible-to-stringify-an-error-using-json-stringify) in JSON.stringify or use a package like https://www.npmjs.com/package/serialize-error (or implement it ourselves) to serialize errors or other objects that may need it

**Comment by gcsabbagh** [comment]
@RemyJeancolas what do you think? I will implement once we decide on something, I need more open source work :)

**Comment by RemyJeancolas** [comment]
@gcssabbagh do you have a code sample for this issue please ?

**Comment by gcsabbagh** [comment]
Well basically ran into the problem in search-indexer. https://github.com/Groupe-Atallah/ms-search/pull/52/files

```
.catch((error) => {
  logger.error("Indexing failed.", null, ["indexer"], {error})
}
```

details section is always empty

```
> const e = new Error('foobar');
undefined
> JSON.stringify(e);
"{}"
> JSON.stringify(e.stack);
""Error: foobar\n    at <anonymous>:1:11""
```

**Comment by RemyJeancolas** [comment]
Never tried to serialize an entire Error before, usually we do something like that and it works properly:
```js
logger.error(error.message, null, ["indexer"], {stack: error.stack})
```
You can either update your code with my snippet or provide a PR on node-logger to fix this specific issue, up to you.

**Comment by gcsabbagh** [comment]
Yup, we have some errors with extra metadata attached to them, so a general solution will work best. I will submit a PR!
